USE master;
CREATE LOGIN [PRODPB01\s.Qualys_SQLDomain] FROM WINDOWS;
GO

USE master;
CREATE USER [PRODPB01\s.Qualys_SQLDomain] FOR LOGIN [PRODPB01\s.Qualys_SQLDomain];
GRANT VIEW ANY DEFINITION TO [PRODPB01\s.Qualys_SQLDomain];
GRANT VIEW ANY DATABASE TO [PRODPB01\s.Qualys_SQLDomain];
ALTER ROLE db_datareader ADD MEMBER [PRODPB01\s.Qualys_SQLDomain];
GRANT EXECUTE TO [PRODPB01\s.Qualys_SQLDomain];
GO

USE model;
CREATE USER [PRODPB01\s.Qualys_SQLDomain] FOR LOGIN [PRODPB01\s.Qualys_SQLDomain];
ALTER ROLE db_datareader ADD MEMBER [PRODPB01\s.Qualys_SQLDomain];
GRANT EXECUTE TO [PRODPB01\s.Qualys_SQLDomain];
GO